name: Deploy to Auth0 main account

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download files from the current repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.20.2'

    - name: Install the auth0-deploy-cli
      run: npm install
  
    - name: Import changes to the Auth0 main account
      env:
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_SECRET }}
      run: npm run export-yaml:main
